[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "python /app/backend/manage.py migrate && gunicorn project.wsgi:application --chdir /app/backend --bind 0.0.0.0:$PORT"
healthcheckPath = "/health/"
